### PR TITLE
Include stream sequence and chunks where applicable.

### LINKED ISSUE #79: Stream in incorrect namespace.
Looks like the stream in `EdvClient.update`
https://github.com/digitalbazaar/edv-client/blob/6bdadb3999140fed1fd9fa33ebc7c9c29e649d4d/EdvClient.js#L249-L252

was not included as part of this commit https://github.com/digitalbazaar/edv-client/commit/1cdbbadb4e26a92bca8636f721725c682aa683b7

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Addresses #78.
Fixes #79.

### CODE REVIEW

File: EdvClient.js [hunk 1]
```diff
@@ -247,7 +247,7 @@ export class EdvClient {
         doc.meta = {};
       }
       // specify stream information
-      doc.meta.stream = {
+      doc.stream = {
```
Comment (dlongley) [inline EdvClient.js:250]: There's a line above this one I can't leave a comment on (246) where we are adding `doc.meta` if it doesn't exist. I suspect we don't need to do that anymore.

File: EdvClient.js [hunk 2]
```diff
@@ -1089,7 +1089,14 @@ export class EdvClient {
     ]);
     delete encrypted.content;
     delete encrypted.meta;
-    delete encrypted.stream;
+
+    if(stream) {
```
Comment (dlongley) [inline EdvClient.js:1093]: I think this needs to be:

```suggestion
    if(encrypted.stream) {
```

Because `stream` is not set when we're doing the final document update (I don't think), after writing the chunks.

File: EdvClient.js [hunk 3]
```diff
@@ -1089,7 +1089,14 @@ export class EdvClient {
...
+      encrypted.stream = {
+        sequence: encrypted.sequence,
+        chunks: (stream || {}).chunks
+      };
```
Comment (dlongley) [inline EdvClient.js:1097]: I think this should just be the subset of things we want to keep in `encrypted.stream`:

```suggestion
      encrypted.stream = {
        sequence: encrypted.stream.sequence,
        chunks: encrypted.stream.chunks
      };
```

File: EdvClient.js (hunk 1 above)
Comment (dmitrizagidulin) [reply EdvClient.js:247]: Removed.

File: EdvClient.js (hunk 3 above)
Comment (dmitrizagidulin) [reply EdvClient.js]: Changed.

File: EdvClient.js (hunk 2 above)
Comment (dmitrizagidulin) [reply EdvClient.js]: Got it, changed.

File: EdvClient.js [hunk 4]
```diff
@@ -95,7 +95,7 @@ export class EdvClient {
    *   from to associate chunked data with this document.
    * @param {number} [options.chunkSize=1048576] - The size, in bytes, of the
    *   chunks to break the incoming stream data into.
-   * @param {object} [options.recipients=[]] - A set of JWE recipients
+   * @param {object[]} [options.recipients=[]] - A set of JWE recipients
```
Comment (dlongley) [inline EdvClient.js:98]: I'm assuming this is the right thing to do with the docs here. I thought maybe it should be `array` or `Array` ... but maybe this is better? I don't know the latest.

File: EdvClient.js [hunk 5]
```diff
@@ -1089,7 +1086,14 @@ export class EdvClient {
...
     delete encrypted.meta;
-    delete encrypted.stream;
+
+    if(encrypted.stream) {
+      encrypted.stream = {
+        sequence: encrypted.stream.sequence,
+        chunks: encrypted.stream.chunks
+      };
+    }
+
```
Comment (dlongley) [inline EdvClient.js:1096]: Since I don't think it makes sense to make this a special code block, I suggest we remove the whitespace. We're setting all the stuff on `encrypted` and `stream` just happens to need a bit of extra work, but it's the same thing as setting the other properties.

```suggestion
    if(encrypted.stream) {
      encrypted.stream = {
        sequence: encrypted.stream.sequence,
        chunks: encrypted.stream.chunks
      };
    }
```

**Review by dlongley — APPROVED** [review]
Thanks!

File: EdvClient.js (hunk 4 above)
Comment (dmitrizagidulin) [reply EdvClient.js:98]: Right, so, the two notations are equivalent - `{object[]}` and `{Array<object>}`. The second one exists so that you can do things like `Array<Array<number>>`

File: EdvClient.js (hunk 5 above)
Comment (dmitrizagidulin) [reply EdvClient.js:1096]: Got it, makes sense.
